### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Obegg** [Universal-Debloater-Alliance/universal-android-debloater#126]
**Describe the feature you want**
The only time the discord channel is linked is here - https://github.com/0x192/universal-android-debloater/issues/923
maybe add it to the readme?

**Comment by Frigyes06** [comment]
Good idea

**Comment by allanonmage** [comment]
I don't know what all the hubub is abotu Discord.  I've had an account for like 10 years, but they have never let me use it, so I basically don't use it.  Something about being banned as I was signing up or some other mind numbing trash, idk.  Yes, I know, "[you]'ve never heard of such a thing".  That's because you use Discord, and people who can't use it, can't use it.

**Comment by adhirajsinghchauhan** [comment]
I'm against using Discord for this repository. It's not the kind of repo that generates conversations by its very nature, so no chat app would be appropriate.

**We'd be fragmenting user/contributor activity and it's just not worth it.** [GitHub Discussions][gh-discussions] is more than enough. That way, everything remains open, easily accessible, and on the same platform. Discord is great for quick chatting, but often vital info is just lost in the sea of other messages. If someone reports a bug there, or asks for a new feature, we'd have to redirect them to GitHub anyway, or file issues on their behalf.

**Right now, we use it primarily for dev talk / internal team discussion, which upon consensus is eventually converted into issues / PRs.**

If we advertise our Discord server and actively encourage people to join, it'll be more headache for us. Any chat-oriented platform is plagued with bad actors that are out to spam or scam people. We'll have to configure a bot of some kind to deal with such things, and maybe "hire" moderators etc. To repeat myself, it's not worth it at all.

[gh-discussions]: https://github.com/Universal-Debloater-Alliance/universal-android-debloater/discussions

**Comment by Frigyes06** [comment]
Discord is not required to use, develop, or contribute to UAD, it is a completely elective tool that most current devs feel comfortable with and find it useful for coordination.

Having said that, I am not against setting up a matrix bridge.

**Comment by AnonymousWP** [comment]
In practice it works different, because not all UAD users have a GitHub account, they won't be able to communicate. What else works different in practice (from what I've seen) is that only big repos have on-going conversations via GitHub Discussions. I think we can allow a Discord server and don't expect it to become big. It's also because some users may want to talk about debloating and helping each other.

I don't think just advertising our Discord server in a humble way via the README will attract hundreds of users at all.
