### ISSUE TITLE
Packages required to be able to add ESIM to Samsung Devices

### ISSUE THREAD

**Issue by GenTEKS** [Universal-Debloater-Alliance/universal-android-debloater#79]
**Your phone model**:
SM-F936U1
**Packages documentation to update:**

```
com.sec.phone
com.sec.android.app.SecSetupWizard...
```

## Documentation Change

**List**: `Samsung`|`Misc`|`OEM` (manufacturer)|`AOSP`|`Pending`|`Carrier` (isp).
**Removal**:  `Recommended` (this can break important features),
or `Unsafe` (this can bootloop the phone or break extremely important features).

### \<com.sec.phone, com.sec.android.app.SecSetupWizard\>

**List**: \<Recommended\> :arrow_right: \<Advanced\>
**Removal**: \<current recommendation list\>
:arrow_right: \<proposed recommendation list\>

### Current description

> Current description

### Proposed description

> Both com.sec.phone & com.sec.android.app.SecSetupWizard must be enabled to be able to add new ESIM's to device. Otherwise menu will spin indefintely.

**Comment by kyoforkshomebrews** [comment]
### com.sec.phone
**List**: `OEM`
**Removal**: `Advanced`
> another test/debug app used to test the proper functioning of phone calls.
On Samsung, both com.sec.phone & com.sec.android.app.SecSetupWizard must be enabled to be able to add new ESIMs to device. Otherwise menu will spin indefinitely.

### com.sec.android.app.SecSetupWizard
**List**: `OEM`
**Removal**: `Advanced`
>Samsung Setup Wizard The first time you turn your device on, a Welcome screen is displayed. It guides you through the basics of setting up your device. It's the setup for Samsung services.
Both com.sec.phone & com.sec.android.app.SecSetupWizard must be enabled to be able to add new ESIMs to device. Otherwise menu will spin indefinitely.
